Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -122,7 +122,8 @@ jobs:
           echo "  document-start: {present: true}" >> yamllint-config.yml
           echo "  trailing-spaces: {level: error}" >> yamllint-config.yml
           echo "  new-line-at-end-of-file: {level: error}" >> yamllint-config.yml
-          yamllint -c yamllint-config.yml .github/workflows/build.yml || { echo "YAML linting failed"; cat .github/workflows/build.yml | nl -ba; exit 1; }
+          yamllint -c yamllint-config.yml .github/workflows/build.yml || \
+            { echo "YAML linting failed"; cat .github/workflows/build.yml | nl -ba; exit 1; }
         shell: bash
       - uses: actions/setup-python@v5
         with:
@@ -225,7 +226,8 @@ jobs:
           echo "            configure = sh.Command('./configure')" >> $LIBFFI_PATH
           echo "            shprint(configure, '--host=' + arch.command_prefix, \\" >> $LIBFFI_PATH
           echo "                    '--prefix={}'.format(self.get_build_dir(arch.arch)), \\" >> $LIBFFI_PATH
-          echo "                    '--disable-builddir', '--enable-static', '--disable-docs', _env=env)" >> $LIBFFI_PATH
+          echo "                    '--disable-builddir', '--enable-static', \\" >> $LIBFFI_PATH
+          echo "                    '--disable-docs', _env=env)" >> $LIBFFI_PATH
           echo "            shprint(sh.make, _env=env)" >> $LIBFFI_PATH
           echo "" >> $LIBFFI_PATH
           echo "recipe = LibffiRecipe()" >> $LIBFFI_PATH
